### ISSUE TITLE
[BE] 백엔드 배포

### ISSUE THREAD

**Issue by qwerty00ui88** [qwerty00ui88/solo-project-1-server#10]
## Tasks

- [x] AWS EC2 인스턴스 생성
- [x] 웹서버 설치 및 관련 설정
- [x] WAS 설치 및 관련 설정

**Comment by qwerty00ui88** [comment]
**에러 사항 설명**
배포 환경에서 쿠키를 읽지 못함

**재현 단계**
1. 로그인 페이지 이동
2. 아이디, 비밀번호 입력
3. 로그인 요청

**예상 결과**
로그인 성공 후 헤더가 `로그인, 회원가입 버튼` -> `로그아웃 버튼`으로 변경되어야 함

**실제 결과**
로그인은 성공했으나 헤더의 버튼이 변경되지 않음

**해결 방법**
같은 도메인의 쿠키만 조회할 수 있다고 함. 하지만 현재 프론트엔드는 `https://solo-project-1-c8107.web.app`, 백엔드는 `http://3.37.61.103:8080`로 도메일이 달라 백엔드에서 설정한 쿠키를 프론트엔드에서 읽지 못함. 따라서 쿠키의 여부에 따라 버튼을 변경하는 프론트엔드 로직에 오류 발생.
-> (해결중)서버를 HTTPS로 전환 후 Samesite=none, secure=true 설정해야 함

**관련 정보**
- 참고 블로그: <a href = "https://gyuturn.tistory.com/74" target="_blank">https://gyuturn.tistory.com/74</a>

**Comment by qwerty00ui88** [comment]
**에러 사항 설명**
배포 환경에서 로그아웃 오류

**재현 단계**
1. 로그인
2. 로그아웃

**예상 결과**
로그아웃 성공 후 헤더가 `로그아웃 버튼` -> `로그인, 회원가입 버튼`으로 변경되어야 함

**실제 결과**
헤더의 버튼이 변경되지 않음

**문제 원인**
로그인 시 JSESSIONID가 중복 생성되어 로그아웃 시 JSESSIONID을 삭제해도 나머지 하나가 남아있어 로그아웃 처리되지 않음

**해결 방법**
해결중

**관련 정보**
