### ISSUE TITLE
[BE] 회원 관련 기능(일반)

### ISSUE THREAD

**Issue by qwerty00ui88** [qwerty00ui88/solo-project-1-server#5]
## Tasks

- [x] 회원가입 API 구현
- [x] 이메일 인증 구현
- [x] 로그인 API 구현
- [x] 로그아웃 API 구현
- [x] 닉네임 중복 확인 API 구현
- [ ] 권한 설정(인터셉터)

**Comment by qwerty00ui88** [comment]
**에러 사항 설명**
로그인 후 코멘트 작성 시 CORS 에러 발생

**재현 단계**
1. 로그인
2. 코멘트 작성

**예상 결과**
코멘트가 작성되어야 함

**실제 결과**
- CORS 에러 발생
976584:1 Access to XMLHttpRequest at 'http://localhost/comment/create' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

**해결 방법**
요청 헤더를 `withCredentials: true`로 설정할 경우 allowedOrigins가 와일드카드(`*`)이면 안됨 
-> allowedOrigins("*")를 allowedOrigins("http://localhost:3000")로 변경

```
// before
@Override
public void addCorsMappings(CorsRegistry registry) {
    registry.addMapping("/**")
        .allowedOrigins("*")
        .allowedMethods("*")
        .allowCredentials(true);
}
```

```
// after
@Override
public void addCorsMappings(CorsRegistry registry) {
    registry.addMapping("/**")
        .allowedOrigins("http://localhost:3000")
        .allowedMethods("*")
        .allowCredentials(true);
}
```

**관련 정보**
- 참고 블로그: <a href = "https://mopil.tistory.com/75" target="_blank">https://mopil.tistory.com/75</a>

**Comment by qwerty00ui88** [comment]
**에러 사항 설명**
이메일 인증 링크 클릭 후 리다이렉트 시 보안 문제

**재현 단계**
1. 사용자가 이메일 인증 링크 클릭
2. `http://localhost:3000/login` 으로 리다이렉트

**예상 결과**
`http://localhost:3000/login`로 리다이렉트 후 로그인 창 렌더링되어야 함

**실제 결과**
`http://localhost:3000/login`으로 리다이렉트는 되지만 `이 사이트는 보안 연결(HTTPS)이 사용되지 않았습니다.` 경고와 사이트 연결할 수 없음 창 표시됨

**해결 방법**
https에서 http로 리다이렉트 불가
=> 해결중

**관련 정보**
- <a href="https://www.quora.com/How-can-I-redirect-HTTPS-to-HTTP-when-I-dont-have-SSL" target="_blank">https://www.quora.com/How-can-I-redirect-HTTPS-to-HTTP-when-I-dont-have-SSL</a>
- <a href="https://velog.io/@ony/HTTP-HTTPS-%EC%B0%A8%EC%9D%B4%EC%99%80-HTTPS%EB%A1%9C-%EB%B3%80%ED%99%98%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95-feat.React" target="_blank">https://velog.io/@ony/HTTP-HTTPS-%EC%B0%A8%EC%9D%B4%EC%99%80-HTTPS%EB%A1%9C-%EB%B3%80%ED%99%98%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95-feat.React</a>

**Comment by qwerty00ui88** [comment]
**학습/적용한 내용**

만료 시간을 `createdAt + 15분`으로 설정하는 방법

**구체적인 변경/적용**

- 트리거 사용
```
CREATE TABLE `emailVerification` (
    `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `userId` INT NOT NULL,
    `token` VARCHAR(512) NOT NULL,
    `purpose` VARCHAR(15) NOT NULL,
    `createdAt` timestamp DEFAULT CURRENT_TIMESTAMP,
    `expiredAt` timestamp DEFAULT CURRENT_TIMESTAMP
);

DELIMITER //

CREATE TRIGGER set_expiredAt
BEFORE INSERT ON emailVerification
FOR EACH ROW
BEGIN
    SET NEW.expiredAt = ADDTIME(NEW.createdAt, '00:15:00');
END//

DELIMITER ;
```

**관련 자료/링크**
- <a href="https://inpa.tistory.com/entry/MYSQL-%F0%9F%93%9A-%ED%8A%B8%EB%A6%AC%EA%B1%B0" target="_blank">https://inpa.tistory.com/entry/MYSQL</a>

**추가 설명**
