### ISSUE TITLE
[BE] 마이페이지

### ISSUE THREAD

**Issue by qwerty00ui88** [qwerty00ui88/solo-project-1-server#6]
## Tasks

- [x] (GET) 로그인 회원의 인생 컨텐츠 리스트
- [x] (DELETE) 인생 컨텐츠 삭제
- [x] (GET) 로그인한 회원이 ①평가한 컨텐츠 ②평가 상태 리스트
- [x] (GET) 로그인한 회원이 코멘트를 작성한 ①컨텐츠 ②평가 상태  ③코멘트 내용 리스트
- [ ] (GET) 로그인한 회원의 회원 정보
- [ ] (POST) 이메일 인증 요청
- [ ] (GET) 현재 위치 요청
- [ ] (PUT) 회원 정보 수정
