### ISSUE TITLE
[BE] 통계 모달

### ISSUE THREAD

**Issue by qwerty00ui88** [qwerty00ui88/solo-project-1-server#9]
## Tasks

- [ ] 통계 모달 페이지 1(지도)
  - [ ] 카카오 지도 API 연결
  - [ ] 지역별 최다 추천 컨텐츠 GET API 구현
  - [ ] 지역별 최다 비추천 컨텐츠 GET API 구현
  - [ ] 지역별 최다 인생 컨텐츠 GET API 구현
- [x] 통계 모달 페이지 2(필터 검색)
  - [x] 필터 검색 API 구현
